## Language: English

## Importing modules

In [150]:
from nltk.corpus import stopwords
 
#you can remove stop words for speed

from nltk.cluster.util import cosine_distance

import numpy as np

import networkx as nx

## Open file and split into sentences

In [151]:
file = open("Text6.txt", "r")

#This file contains one paragraph of multiple sentences

filedata = file.readlines()

article = filedata[0].split(". ") #Just do the first paragraph

sentences = []

for sentence in article:

         print(sentence)

         sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

Scientists conducting fieldwork in the Amazon rainforest have identified a new species of orchid
Named "Dendrobium Amazonian," this orchid boasts vibrant purple flowers and grows exclusively in the dense Amazonian vegetation
The discovery underscores the importance of conservation efforts in preserving biodiversity in threatened ecosystems like the Amazon.


## Our data: a list of sentences

In [152]:
print("Sentences are ", sentences)

Sentences are  [['Scientists', 'conducting', 'fieldwork', 'in', 'the', 'Amazon', 'rainforest', 'have', 'identified', 'a', 'new', 'species', 'of', 'orchid'], ['Named', '"Dendrobium', 'Amazonian,"', 'this', 'orchid', 'boasts', 'vibrant', 'purple', 'flowers', 'and', 'grows', 'exclusively', 'in', 'the', 'dense', 'Amazonian', 'vegetation'], ['The', 'discovery', 'underscores', 'the', 'importance', 'of', 'conservation', 'efforts', 'in', 'preserving', 'biodiversity', 'in', 'threatened', 'ecosystems', 'like', 'the', 'Amazon.']]


## Function to calculate similarity
## (count the number of common words)

In [153]:
def sentence_similarity(sent1, sent2 ):

    sent1 = [w.lower() for w in sent1]

    sent2 = [w.lower() for w in sent2]

    all_words = list(set(sent1 + sent2))

    vector1 = [0] * len(all_words)

    vector2 = [0] * len(all_words)

        # build the vector for the first sentence

    for w in sent1:

         vector1[all_words.index(w)] += 1

       # build the vector for the second sentence

    for w in sent2:

         vector2[all_words.index(w)] += 1

    return 1 - cosine_distance(vector1, vector2)

## Create the similarity matrix

In [154]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
for idx1 in range(len(sentences)):
    for idx2 in range(len(sentences)):
        if idx1 == idx2:  # ignore if both are same sentences
            continue
        similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Similarity matrix:\n", similarity_matrix)

Similarity matrix:
 [[0.         0.19446112 0.32071349]
 [0.19446112 0.         0.24253563]
 [0.32071349 0.24253563 0.        ]]


## Get the pagerank scores

In [155]:
# Step 3 - Rank sentences in similarity martix

sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)

scores = nx.pagerank(sentence_similarity_graph)

print("scores", scores)

scores {0: 0.3389310970669074, 1: 0.2933381671575834, 2: 0.36773073577550913}


## Sort sentences by pagerank

In [156]:
# Step 4 - Sort the rank and pick top sentences

ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)

print("Indexes of top ranked_sentence order are \n\n",

ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.36773073577550913, ['The', 'discovery', 'underscores', 'the', 'importance', 'of', 'conservation', 'efforts', 'in', 'preserving', 'biodiversity', 'in', 'threatened', 'ecosystems', 'like', 'the', 'Amazon.']), (0.3389310970669074, ['Scientists', 'conducting', 'fieldwork', 'in', 'the', 'Amazon', 'rainforest', 'have', 'identified', 'a', 'new', 'species', 'of', 'orchid']), (0.2933381671575834, ['Named', '"Dendrobium', 'Amazonian,"', 'this', 'orchid', 'boasts', 'vibrant', 'purple', 'flowers', 'and', 'grows', 'exclusively', 'in', 'the', 'dense', 'Amazonian', 'vegetation'])]


## Pick the top “n” sentences

In [157]:

#Step 5 - How many sentences to pick

n = int(input("How many sentences do you want in the summary? "))

#n=2

summarize_text = []

for i in range(n):

      summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary?  3


## printing summary

In [158]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 The discovery underscores the importance of conservation efforts in preserving biodiversity in threatened ecosystems like the Amazon.. Scientists conducting fieldwork in the Amazon rainforest have identified a new species of orchid. Named "Dendrobium Amazonian," this orchid boasts vibrant purple flowers and grows exclusively in the dense Amazonian vegetation


## Language: Spanish 

## Importing modules


In [159]:
from nltk.corpus import stopwords
 
#you can remove stop words for speed

from nltk.cluster.util import cosine_distance

import numpy as np

import networkx as nx


## Open file and split into sentences

In [160]:
file = open("Text7.txt", "r")

#This file contains one paragraph of multiple sentences

filedata = file.readlines()

article = filedata[0].split(". ") #Just do the first paragraph

sentences = []

for sentence in article:

         print(sentence)

         sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

Científicos que realizan trabajo de campo en la selva amazónica han identificado una nueva especie de orquídea
Llamada "Dendrobium Amazonian", esta orquídea cuenta con flores moradas vibrantes y crece exclusivamente en la densa vegetación amazónica
El descubrimiento subraya la importancia de los esfuerzos de conservación para preservar la biodiversidad en ecosistemas amenazados como el amazónico.



## Our data: a list of sentences

In [161]:
print("Sentences are ", sentences)

Sentences are  [['Científicos', 'que', 'realizan', 'trabajo', 'de', 'campo', 'en', 'la', 'selva', 'amazónica', 'han', 'identificado', 'una', 'nueva', 'especie', 'de', 'orquídea'], ['Llamada', '"Dendrobium', 'Amazonian",', 'esta', 'orquídea', 'cuenta', 'con', 'flores', 'moradas', 'vibrantes', 'y', 'crece', 'exclusivamente', 'en', 'la', 'densa', 'vegetación', 'amazónica'], ['El', 'descubrimiento', 'subraya', 'la', 'importancia', 'de', 'los', 'esfuerzos', 'de', 'conservación', 'para', 'preservar', 'la', 'biodiversidad', 'en', 'ecosistemas', 'amenazados', 'como', 'el', 'amazónico.\n']]


## Function to calculate similarity
## (count the number of common words)

In [162]:
def sentence_similarity(sent1, sent2 ):

    sent1 = [w.lower() for w in sent1]

    sent2 = [w.lower() for w in sent2]

    all_words = list(set(sent1 + sent2))

    vector1 = [0] * len(all_words)

    vector2 = [0] * len(all_words)

        # build the vector for the first sentence

    for w in sent1:

         vector1[all_words.index(w)] += 1

       # build the vector for the second sentence

    for w in sent2:

         vector2[all_words.index(w)] += 1

    return 1 - cosine_distance(vector1, vector2)

## Create the similarity matrix

In [163]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
for idx1 in range(len(sentences)):
    for idx2 in range(len(sentences)):
        if idx1 == idx2:  # ignore if both are same sentences
            continue
        similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Similarity matrix:\n", similarity_matrix)

Similarity matrix:
 [[0.         0.21629523 0.31494489]
 [0.21629523 0.         0.13867505]
 [0.31494489 0.13867505 0.        ]]


## Get the pagerank scores

In [164]:
# Step 3 - Rank sentences in similarity martix

sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)

scores = nx.pagerank(sentence_similarity_graph)

print("scores", scores)

scores {0: 0.3901897983187782, 1: 0.27264827833165, 2: 0.337161923349571}


## Sort sentences by pagerank

In [165]:
# Step 4 - Sort the rank and pick top sentences

ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)

print("Indexes of top ranked_sentence order are \n\n",

ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.3901897983187782, ['Científicos', 'que', 'realizan', 'trabajo', 'de', 'campo', 'en', 'la', 'selva', 'amazónica', 'han', 'identificado', 'una', 'nueva', 'especie', 'de', 'orquídea']), (0.337161923349571, ['El', 'descubrimiento', 'subraya', 'la', 'importancia', 'de', 'los', 'esfuerzos', 'de', 'conservación', 'para', 'preservar', 'la', 'biodiversidad', 'en', 'ecosistemas', 'amenazados', 'como', 'el', 'amazónico.\n']), (0.27264827833165, ['Llamada', '"Dendrobium', 'Amazonian",', 'esta', 'orquídea', 'cuenta', 'con', 'flores', 'moradas', 'vibrantes', 'y', 'crece', 'exclusivamente', 'en', 'la', 'densa', 'vegetación', 'amazónica'])]


## Pick the top “n” sentences

In [168]:

#Step 5 - How many sentences to pick

n = int(input("How many sentences do you want in the summary? "))

#n=2

summarize_text = []

for i in range(n):

      summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary?  3


## printing summary

In [169]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 Científicos que realizan trabajo de campo en la selva amazónica han identificado una nueva especie de orquídea. El descubrimiento subraya la importancia de los esfuerzos de conservación para preservar la biodiversidad en ecosistemas amenazados como el amazónico.
. Llamada "Dendrobium Amazonian", esta orquídea cuenta con flores moradas vibrantes y crece exclusivamente en la densa vegetación amazónica


## Language: Telugu

## Importing modules

In [170]:
from nltk.corpus import stopwords
 
#you can remove stop words for speed

from nltk.cluster.util import cosine_distance

import numpy as np

import networkx as nx

## Open file and split into sentences

In [171]:
file = open("Text8.txt", "r")

#This file contains one paragraph of multiple sentences

filedata = file.readlines()

article = filedata[0].split(". ") #Just do the first paragraph

sentences = []

for sentence in article:

         print(sentence)

         sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

ఈ హొందికలు తెలిపిన ఈ కొత్త సాంకేతిక సాధనం సంచార విధానాలులో ఒక మార్పును సంజీవిస్తుంది
అతని అభిమానాన్ని అనుసరించి, వ్యక్తులు త్వరిత మరియు కనిష్ఠ సమయంలో సమాచారం వ్యవస్థలను చేంజ్ చేయగలిగేలా అనుభవిస్తుండారు
ఇది మాత్రమే కాక, అందుబాటులో ఉత్పత్తి మీరు కొన్ని లోపాలను అనుభవించాలి
మరియు ఈ సాంకేతిక ప్రవృత్తి అంతా ఎందుకంటి సమాచారం నిలుస్తోంది.


## Our data: a list of sentences

In [172]:
print("Sentences are ", sentences)

Sentences are  [['ఈ', 'హొందికలు', 'తెలిపిన', 'ఈ', 'కొత్త', 'సాంకేతిక', 'సాధనం', 'సంచార', 'విధానాలులో', 'ఒక', 'మార్పును', 'సంజీవిస్తుంది'], ['అతని', 'అభిమానాన్ని', 'అనుసరించి,', 'వ్యక్తులు', 'త్వరిత', 'మరియు', 'కనిష్ఠ', 'సమయంలో', 'సమాచారం', 'వ్యవస్థలను', 'చేంజ్', 'చేయగలిగేలా', 'అనుభవిస్తుండారు'], ['ఇది', 'మాత్రమే', 'కాక,', 'అందుబాటులో', 'ఉత్పత్తి', 'మీరు', 'కొన్ని', 'లోపాలను', 'అనుభవించాలి'], ['మరియు', 'ఈ', 'సాంకేతిక', 'ప్రవృత్తి', 'అంతా', 'ఎందుకంటి', 'సమాచారం', 'నిలుస్తోంది.']]


## Function to calculate similarity
## (count the number of common words)

In [173]:
def sentence_similarity(sent1, sent2 ):

    sent1 = [w.lower() for w in sent1]

    sent2 = [w.lower() for w in sent2]

    all_words = list(set(sent1 + sent2))

    vector1 = [0] * len(all_words)

    vector2 = [0] * len(all_words)

        # build the vector for the first sentence

    for w in sent1:

         vector1[all_words.index(w)] += 1

       # build the vector for the second sentence

    for w in sent2:

         vector2[all_words.index(w)] += 1

    return 1 - cosine_distance(vector1, vector2)

## Create the similarity matrix

In [174]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
for idx1 in range(len(sentences)):
    for idx2 in range(len(sentences)):
        if idx1 == idx2:  # ignore if both are same sentences
            continue
        similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Similarity matrix:\n", similarity_matrix)

Similarity matrix:
 [[0.         0.         0.         0.28347335]
 [0.         0.         0.         0.19611614]
 [0.         0.         0.         0.        ]
 [0.28347335 0.19611614 0.         0.        ]]


## Get the pagerank scores

In [175]:
# Step 3 - Rank sentences in similarity martix

sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)

scores = nx.pagerank(sentence_similarity_graph)

print("scores", scores)

scores {0: 0.28039708734500773, 1: 0.20866250630758768, 2: 0.04761904761904763, 3: 0.463321358728357}


## Sort sentences by pagerank

In [176]:
# Step 4 - Sort the rank and pick top sentences

ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)

print("Indexes of top ranked_sentence order are \n\n",

ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.463321358728357, ['మరియు', 'ఈ', 'సాంకేతిక', 'ప్రవృత్తి', 'అంతా', 'ఎందుకంటి', 'సమాచారం', 'నిలుస్తోంది.']), (0.28039708734500773, ['ఈ', 'హొందికలు', 'తెలిపిన', 'ఈ', 'కొత్త', 'సాంకేతిక', 'సాధనం', 'సంచార', 'విధానాలులో', 'ఒక', 'మార్పును', 'సంజీవిస్తుంది']), (0.20866250630758768, ['అతని', 'అభిమానాన్ని', 'అనుసరించి,', 'వ్యక్తులు', 'త్వరిత', 'మరియు', 'కనిష్ఠ', 'సమయంలో', 'సమాచారం', 'వ్యవస్థలను', 'చేంజ్', 'చేయగలిగేలా', 'అనుభవిస్తుండారు']), (0.04761904761904763, ['ఇది', 'మాత్రమే', 'కాక,', 'అందుబాటులో', 'ఉత్పత్తి', 'మీరు', 'కొన్ని', 'లోపాలను', 'అనుభవించాలి'])]


## Pick the top “n” sentences

In [177]:

#Step 5 - How many sentences to pick

n = int(input("How many sentences do you want in the summary? "))

#n=2

summarize_text = []

for i in range(n):

      summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary?  4


## printing summary

In [178]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 మరియు ఈ సాంకేతిక ప్రవృత్తి అంతా ఎందుకంటి సమాచారం నిలుస్తోంది.. ఈ హొందికలు తెలిపిన ఈ కొత్త సాంకేతిక సాధనం సంచార విధానాలులో ఒక మార్పును సంజీవిస్తుంది. అతని అభిమానాన్ని అనుసరించి, వ్యక్తులు త్వరిత మరియు కనిష్ఠ సమయంలో సమాచారం వ్యవస్థలను చేంజ్ చేయగలిగేలా అనుభవిస్తుండారు. ఇది మాత్రమే కాక, అందుబాటులో ఉత్పత్తి మీరు కొన్ని లోపాలను అనుభవించాలి


## Language: Hindi

In [179]:
from nltk.corpus import stopwords
 
#you can remove stop words for speed

from nltk.cluster.util import cosine_distance

import numpy as np

import networkx as nx

## Open file and split into sentences

In [180]:
file = open("Text9.txt", "r")

#This file contains one paragraph of multiple sentences

filedata = file.readlines()

article = filedata[0].split(". ") #Just do the first paragraph

sentences = []

for sentence in article:

         print(sentence)

         sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

डेटा साइंस आजकल एक महत्वपूर्ण क्षेत्र बन चुका है जो तकनीकी विज्ञान, सांख्यिकी, और गहरी विवेचना का संगम है। यह विज्ञान डेटा के संग्रहण, विश्लेषण, और उससे संबंधित निर्णय लेने की क्षमता को संवर्धित करता है। डेटा साइंस का महत्व आजकल विभिन्न क्षेत्रों में बढ़ता जा रहा है, जैसे कि वित्त, स्वास्थ्य, विपणन, और सामाजिक विज्ञान। इसके साथ ही, डेटा साइंस भविष्य में और भी महत्वपूर्ण होने की संभावना है।भविष्य में, डेटा साइंस का उपयोग और विस्तार और भी बढ़ेगा। बड़ी और छोटी कंपनियों, सरकारी संस्थाएं, और अन्य संगठन डेटा साइंस का उपयोग करके अपने विभागीय और व्यावसायिक लक्ष्यों को प्राप्त करेंगे। डेटा साइंस विश्व की विकासशीलता में महत्वपूर्ण भूमिका निभाएगा, जो नए नए संभावनाओं को समय-समय पर खोलेगा। अतीत में डेटा साइंस ने कई क्षेत्रों में क्रांतिकारी परिवर्तन लाए हैं, और आने वाले समय में भी इसका महत्व और विस्तार और भी बढ़ेगा। यह उद्योग, विज्ञान, स्वास्थ्य देखभाल, सामाजिक विज्ञान, और अन्य क्षेत्रों में नए और उपयोगी निर्णय लेने में सहायक होगा। इस तरह, डेटा साइंस न केवल वर्तमान में बल्कि भविष्य में भी हमारे जीव

## Our data: a list of sentences

In [181]:
print("Sentences are ", sentences)

Sentences are  [['डेटा', 'साइंस', 'आजकल', 'एक', 'महत्वपूर्ण', 'क्षेत्र', 'बन', 'चुका', 'है', 'जो', 'तकनीकी', 'विज्ञान,', 'सांख्यिकी,', 'और', 'गहरी', 'विवेचना', 'का', 'संगम', 'है।', 'यह', 'विज्ञान', 'डेटा', 'के', 'संग्रहण,', 'विश्लेषण,', 'और', 'उससे', 'संबंधित', 'निर्णय', 'लेने', 'की', 'क्षमता', 'को', 'संवर्धित', 'करता', 'है।', 'डेटा', 'साइंस', 'का', 'महत्व', 'आजकल', 'विभिन्न', 'क्षेत्रों', 'में', 'बढ़ता', 'जा', 'रहा', 'है,', 'जैसे', 'कि', 'वित्त,', 'स्वास्थ्य,', 'विपणन,', 'और', 'सामाजिक', 'विज्ञान।', 'इसके', 'साथ', 'ही,', 'डेटा', 'साइंस', 'भविष्य', 'में', 'और', 'भी', 'महत्वपूर्ण', 'होने', 'की', 'संभावना', 'है।भविष्य', 'में,', 'डेटा', 'साइंस', 'का', 'उपयोग', 'और', 'विस्तार', 'और', 'भी', 'बढ़ेगा।', 'बड़ी', 'और', 'छोटी', 'कंपनियों,', 'सरकारी', 'संस्थाएं,', 'और', 'अन्य', 'संगठन', 'डेटा', 'साइंस', 'का', 'उपयोग', 'करके', 'अपने', 'विभागीय', 'और', 'व्यावसायिक', 'लक्ष्यों', 'को', 'प्राप्त', 'करेंगे।', 'डेटा', 'साइंस', 'विश्व', 'की', 'विकासशीलता', 'में', 'महत्वपूर्ण', 'भूमिका', 'निभाएगा,', 'जो',

## Function to calculate similarity
## (count the number of common words)

In [182]:
def sentence_similarity(sent1, sent2 ):

    sent1 = [w.lower() for w in sent1]

    sent2 = [w.lower() for w in sent2]

    all_words = list(set(sent1 + sent2))

    vector1 = [0] * len(all_words)

    vector2 = [0] * len(all_words)

        # build the vector for the first sentence

    for w in sent1:

         vector1[all_words.index(w)] += 1

       # build the vector for the second sentence

    for w in sent2:

         vector2[all_words.index(w)] += 1

    return 1 - cosine_distance(vector1, vector2)

## Create the similarity matrix

In [183]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
for idx1 in range(len(sentences)):
    for idx2 in range(len(sentences)):
        if idx1 == idx2:  # ignore if both are same sentences
            continue
        similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Similarity matrix:\n", similarity_matrix)

Similarity matrix:
 [[0.]]


## Get the pagerank scores

In [184]:
# Step 3 - Rank sentences in similarity martix

sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)

scores = nx.pagerank(sentence_similarity_graph)

print("scores", scores)

scores {0: 1.0}


## Sort sentences by pagerank

In [185]:
# Step 4 - Sort the rank and pick top sentences

ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)

print("Indexes of top ranked_sentence order are \n\n",

ranked_sentence)

Indexes of top ranked_sentence order are 

 [(1.0, ['डेटा', 'साइंस', 'आजकल', 'एक', 'महत्वपूर्ण', 'क्षेत्र', 'बन', 'चुका', 'है', 'जो', 'तकनीकी', 'विज्ञान,', 'सांख्यिकी,', 'और', 'गहरी', 'विवेचना', 'का', 'संगम', 'है।', 'यह', 'विज्ञान', 'डेटा', 'के', 'संग्रहण,', 'विश्लेषण,', 'और', 'उससे', 'संबंधित', 'निर्णय', 'लेने', 'की', 'क्षमता', 'को', 'संवर्धित', 'करता', 'है।', 'डेटा', 'साइंस', 'का', 'महत्व', 'आजकल', 'विभिन्न', 'क्षेत्रों', 'में', 'बढ़ता', 'जा', 'रहा', 'है,', 'जैसे', 'कि', 'वित्त,', 'स्वास्थ्य,', 'विपणन,', 'और', 'सामाजिक', 'विज्ञान।', 'इसके', 'साथ', 'ही,', 'डेटा', 'साइंस', 'भविष्य', 'में', 'और', 'भी', 'महत्वपूर्ण', 'होने', 'की', 'संभावना', 'है।भविष्य', 'में,', 'डेटा', 'साइंस', 'का', 'उपयोग', 'और', 'विस्तार', 'और', 'भी', 'बढ़ेगा।', 'बड़ी', 'और', 'छोटी', 'कंपनियों,', 'सरकारी', 'संस्थाएं,', 'और', 'अन्य', 'संगठन', 'डेटा', 'साइंस', 'का', 'उपयोग', 'करके', 'अपने', 'विभागीय', 'और', 'व्यावसायिक', 'लक्ष्यों', 'को', 'प्राप्त', 'करेंगे।', 'डेटा', 'साइंस', 'विश्व', 'की', 'विकासशीलता', 'में', 'महत्व

## Pick the top “n” sentences

In [186]:

#Step 5 - How many sentences to pick

n = int(input("How many sentences do you want in the summary? "))

#n=2

summarize_text = []

for i in range(n):

      summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary?  1


## printing summary

In [187]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 डेटा साइंस आजकल एक महत्वपूर्ण क्षेत्र बन चुका है जो तकनीकी विज्ञान, सांख्यिकी, और गहरी विवेचना का संगम है। यह विज्ञान डेटा के संग्रहण, विश्लेषण, और उससे संबंधित निर्णय लेने की क्षमता को संवर्धित करता है। डेटा साइंस का महत्व आजकल विभिन्न क्षेत्रों में बढ़ता जा रहा है, जैसे कि वित्त, स्वास्थ्य, विपणन, और सामाजिक विज्ञान। इसके साथ ही, डेटा साइंस भविष्य में और भी महत्वपूर्ण होने की संभावना है।भविष्य में, डेटा साइंस का उपयोग और विस्तार और भी बढ़ेगा। बड़ी और छोटी कंपनियों, सरकारी संस्थाएं, और अन्य संगठन डेटा साइंस का उपयोग करके अपने विभागीय और व्यावसायिक लक्ष्यों को प्राप्त करेंगे। डेटा साइंस विश्व की विकासशीलता में महत्वपूर्ण भूमिका निभाएगा, जो नए नए संभावनाओं को समय-समय पर खोलेगा। अतीत में डेटा साइंस ने कई क्षेत्रों में क्रांतिकारी परिवर्तन लाए हैं, और आने वाले समय में भी इसका महत्व और विस्तार और भी बढ़ेगा। यह उद्योग, विज्ञान, स्वास्थ्य देखभाल, सामाजिक विज्ञान, और अन्य क्षेत्रों में नए और उपयोगी निर्णय लेने में सहायक होगा। इस तरह, डेटा साइंस न केवल वर्तमान में बल्कि भविष्